### ISSUE TITLE
Can't debug erro

### ISSUE THREAD

**Issue by andrewfam** [jonashagstedt/swampdragon#105]

**Comment by andrewfam** [comment]
<script>
var OrdersApp = angular.module('OrdersApp', [
    'SwampDragonServices',
    'OrdersControllers'
]);


var OrdersControllers = angular.module('OrdersControllers', []);

OrdersControllers.controller('OrderCtrl', ['$scope', '$dragon', function ($scope, $dragon) {
    $scope.orders = [];
    $scope.channel = 'orders';

    $dragon.onReady(function() {
        $dragon.subscribe('orders', $scope.channel, {site_id: {{ request.session.site_id }}}).then(function(response) {
            $scope.dataMapper = new DataMapper(response.data);
        });

        $dragon.getList('orders', {site_id: {{ request.session.site_id }}}).then(function(response) {
            console.log(response.data)
            console.log("Getting stuff");
            $scope.orders = response.data;
        });
    });

    $dragon.onChannelMessage(function(channels, message) {
        console.log('Test dataMapper')
        if (indexOf.call(channels, $scope.channel) > -1) {
            console.log('Test dataMapper')
            $scope.$apply(function() {
                console.log('Test dataMapper')
                $scope.dataMapper.mapData($scope.orders, message);
            });
        }
    });
}]);
</script>

**Comment by jonashagstedt** [comment]
This:

    $dragon.subscribe('orders', $scope.channel, {site_id: {{ request.session.site_id }}}).then(function(response) {
        $scope.dataMapper = new DataMapper(response.data);
    });

implies that you are subscribing to any `Order` that has a site_id of X, but according to your model there is no such property.

**Comment by jonashagstedt** [comment]
Also as an additional note: you should override the get_subscription_contexts instead of trusting what is sent from JavaScript

**Comment by andrewfam** [comment]
Hey thanks for the help i still can't get this to work

Server.py results
Traceback (most recent call last):
  File "/Users/andrewfam/.virtualenvs/oshop/lib/python2.7/site-packages/sockjs/tornado/transports/websocket.py", line 60, in on_message
    self.session.on_messages(msg)
  File "/Users/andrewfam/.virtualenvs/oshop/lib/python2.7/site-packages/sockjs/tornado/session.py", line 423, in on_messages
    self.conn.on_message(msg)
  File "/Users/andrewfam/.virtualenvs/oshop/lib/python2.7/site-packages/swampdragon/connections/sockjs_connection.py", line 90, in on_message
    raise e
ValueError: need more than 1 value to unpack
ERROR:tornado.general:WebSocket
Traceback (most recent call last):
  File "/Users/andrewfam/.virtualenvs/oshop/lib/python2.7/site-packages/sockjs/tornado/transports/websocket.py", line 60, in on_message
    self.session.on_messages(msg)
  File "/Users/andrewfam/.virtualenvs/oshop/lib/python2.7/site-packages/sockjs/tornado/session.py", line 423, in on_messages
    self.conn.on_message(msg)
  File "/Users/andrewfam/.virtualenvs/oshop/lib/python2.7/site-packages/swampdragon/connections/sockjs_connection.py", line 90, in on_message
    raise e
ValueError: need more than 1 value to unpack

from swampdragon.serializers.model_serializer import ModelSerializer

class OrderSerializer(ModelSerializer):
    class Meta:
        model = 'Order'
        publish_fields = ['id',]

from swampdragon import route_handler
from swampdragon.route_handler import ModelRouter
from cartridge.shop.models import Order
from own_orders.serializers import OrderSerializer

class OrderRouter(ModelRouter):
    route_name = 'orders'
    serializer_class = OrderSerializer
    model = Order

    def get_object(self, **kwargs):
        return self.model.objects.get(pk=kwargs['id'])
        
    def get_query_set(self, **kwargs):
    	import pdb; pdb.set_trace()
        return self.model.filter(site=kwargs['site_id'])

route_handler.register(OrderRouter)

OrdersControllers.controller('OrderCtrl', ['$scope', '$dragon', function ($scope, $dragon) {
    $scope.orders = [];
    $scope.channel = 'orders';

    $dragon.onReady(function() {
        $dragon.subscribe('orders', $scope.channel, {site_id: {{ request.session.site_id }}}).then(function(response) {
            $scope.dataMapper = new DataMapper(response.data);
            console.log($scope.dataMapper);
        });

        $dragon.getList('orders', {site_id: {{ request.session.site_id }}}).then(function(response) {
            $scope.orders = response.data;
            console.log(response.data);
        });
    });

    $dragon.onChannelMessage(function(channels, message) {
        if (indexOf.call(channels, $scope.channel) > -1) {
            console.log('Test dataMapper')
            $scope.$apply(function() {
                console.log('Test dataMapper')
                $scope.dataMapper.mapData($scope.orders, message);
            });
        }
    });
}]);

**Comment by jonashagstedt** [comment]
Could you put a breakpoint here:
https://github.com/jonashagstedt/swampdragon/blob/master/swampdragon/connections/sockjs_connection.py#L89

And look at the value of `data` and let me know what it is?

**Comment by andrewfam** [comment]
Hey I've made some progress. Not too sure why the Router comes up blank

class OrderRouter(BaseModel):
    route_name = 'orders'
    serializer_class = OrderSerializer
    model = Order

    def get_object(self, **kwargs):
        return self.model.objects.get(pk=kwargs['id'])
        
    def get_query_set(self, **kwargs):
    	import pdb; pdb.set_trace()
        return self.model.objects.filter(site=kwargs['site_id'])

Order.objects.all() returns []

**Comment by cho-is** [comment]
I still think that SwampDragon is amazing.
But I find it really really hard to debug.

**Comment by josefmonje** [comment]
This particular line:
https://github.com/jonashagstedt/swampdragon/blob/master/swampdragon/connections/sockjs_connection.py#L87

is giving me:
```
ERROR:tornado.general:WebSocket
Traceback (most recent call last):
  File "C:\Users\...\Envs\swamp\lib\site-packages\sockjs\tornado\transports\websocket.py", line 60, in on_message
    self.session.on_messages(msg)
  File "C:\Users\...\Envs\swamp\lib\site-packages\sockjs\tornado\session.py", line 424, in on_messages
    self.conn.on_message(msg)
  File "C:\Users\...\Envs\swamp\lib\site-packages\swampdragon\connections\sockjs_connection.py", line 90, in on_message
    raise e
**FieldError: Cannot resolve keyword 'Dragon_list' into field. Choices are: done, dragon_list, dragon_list_id, id, text**
ERROR:tornado.application:Uncaught exception in /data/368/uxx6hf3e/websocket
Traceback (most recent call last):
  File "C:\Users\...\Envs\swamp\lib\site-packages\tornado\websocket.py", line 415, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\...\Envs\swamp\lib\site-packages\sockjs\tornado\transports\websocket.py", line 70, in on_message
    self.abort_connection()
  File "C:\Users\...\Envs\swamp\lib\site-packages\sockjs\tornado\websocket.py", line 28, in abort_connection
    self.ws_connection._abort()
AttributeError: 'NoneType' object has no attribute '_abort'
```

and I can't find where to fix it.
